name: aflutter_craft
description: A platform for neural art style transfer.
publish_to: "none"
version: 1.0.0+1

# default flutter stuff
environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/texts/

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: any # state management
  http: any # fetching stuff from the web
  google_fonts: any # custom fonts
  file_selector: any # corss platform file selection
  file_selector_linux: any
  file_selector_windows: any
  file_selector_macos: any
  cached_network_image: any # fetch network image
  social_share: any # share to specific social media
  flutter_cache_manager: any # manage cache of network iamges
  path_provider: any # provide common used paths in a platform
  url_launcher: any # launch a link in platform browser
  shared_preferences: any # for saving some app settings to device
  showcaseview: any # showcase app features on first time run
  image_gallery_saver: any # for saving images to gallery (mobile)
  window_size: # set the window size and other stuff
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: any # generate splash screen for Android/IOS and Web
  flutter_launcher_icons: any # generate IOS/Android app icons

# native splash settings
flutter_native_splash:
  color: "#f1f1f1"
  color_dark: "#0f111a"
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

# App icon settings
flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ff4151"
  adaptive_icon_foreground: "assets/images/logo.png"
